neuralzero/neuralzero/apps/auth/urls.py
from django.urls import path

from . import views

app_name = "auth"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

neuralzero/neuralzero/apps/neural/urls.py
from django.urls import path

from . import views

app_name = "neural"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:network_id>/", views.view_network, name="view"),
    path("<int:network_id>/edit/", views.view_network, name="edit"),
]

neuralzero/neuralzero/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls", namespace="social")),
    path("neural", include("neuralzero.apps.neural.urls", namespace="neural")),
    path("", include("neuralzero.apps.auth.urls", namespace="auth")),
]

neuralzero/neuralzero/apps/neural/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.


class Network(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=80)

neuralzero/neuralzero/apps/neural/views.py
from django.shortcuts import render

from ...utils.helpers import get_network_for_user_or_404

# Create your views here.


def index(request):
    return render(request, "neural/index.html")


def view_network(request, network_id):
    network = get_network_for_user_or_404(request.user, id=network_id)

    return render(request, "neural/view.html", {"network": network})


def edit_network(request, network_id):
    network = get_network_for_user_or_404(request.user, id=network_id)

    return render(request, "neural/edit.html", {"network": network})

neuralzero/neuralzero/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}NeuralZero{% block titlesuffix %}{% endblock %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:100italic,400italic,700italic,100,400,700" />
  <link rel="stylesheet" href="{% static 'vendor/jquery-ui/jquery-ui-1.12.1.min.css' %}" />
  <script src="{% static 'js/vendor/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-ui/jquery-ui-1.12.1.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/selectize/selectize.default.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/highlight/styles/default.css' %}">
  <script src="{% static 'vendor/highlight/highlight.pack.js' %}"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <script type="text/javascript" src="{% static 'vendor/selectize/selectize.min.js' %}"></script>
  <script>$(function(){$(".continuous-progress").css({height: "15px"}).progressbar({value: false})});</script>
  {% block head %}{% endblock %}
</head>
<body>
  <div id="nav">
    <ul>
      <li><a href="{% url 'auth:index' %}"><h1>NeuralZero</h1></a></li>
      {% if request.user.is_authenticated %}
        {% if nav_item %}
          <li><i class="fa fa-chevron-right"></i></li>
          <li><a href="">{{ nav_item }}</a></li>
        {% endif %}
        <li class="right"><i class="fa fa-sign-out"></i><a href="{% url 'auth:logout' %}">Logout ({{ request.user.username }})</a></li>
      {% endif %}
    </ul>
  </div>
  <div id="content">
    <div id="main">
      {% block main %}
      {% endblock %}
    </div>
    <br>
  </div>
</body>
</html>

neuralzero/neuralzero/templates/neural/index.html
{% extends "base.html" %}

{% block titlesuffix %}: Home{% endblock %}

{% block main %}
    {% for network in networks %}
    {% endfor %}
{% endblock %}

neuralzero/neuralzero/templates/neural/view.html
{% extends "base.html" %}

{% block titlesuffix %}: {{ network.name }}{% endblock %}